import Head from 'next/head'
import HomeScreen from '@/components/screens/Home'
import { useThemeContext } from '@/context'


export default function Home() {

  const {themeLoaded} = useThemeContext();

  return (
    <>
      <Head>
        <title>Snake Game</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        {themeLoaded && <HomeScreen />}
    </>
  )
}
